set(PROJECT_NAME tinyxml)
set(PACKAGE tinyxml)
set(MAJOR 2)
set(MINOR 6)
set(PATCH 2)
set(TWEAK )
set(VERSION_STRING ${MAJOR}.${MINOR}.${PATCH})

ExternalProject_Add(${PROJECT_NAME}
	URL ${CMAKE_CURRENT_SOURCE_DIR}/${PACKAGE}-${VERSION_STRING}.tar.xz
	URL_MD5 bb76d6a3b31fa967c6148cfa1c3d0dc2 
	PREFIX ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}
	INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
	UPDATE_COMMAND ""
	CMAKE_ARGS 
		-DCMAKE_PREFIX_PATH=<INSTALL_DIR>
		-DCMAKE_MODULE_PATH=${CMAKE_SOURCE_DIR}/cmake
		-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>	
		-DCMAKE_INSTALL_LIBDIR=lib		
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DBUILD_STATIC_LIBS=FALSE
		-DBUILD_SHARED_LIBS=TRUE	
	LOG_CONFIGURE 1
	LOG_BUILD 1
	LOG_INSTALL 1
)
